apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: token-images-prd
  namespace: token-images
spec:
  tokenSecret:
    name: doppler-token-images-prd
    namespace: token-images
  project: token-images
  config: prd
  managedSecret:
    name: token-images-prd
    namespace: token-images
    type: Opaque

    