name: Build and Push Image
on:
  push:
    branches: feature/kube_config

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_REGION: eu-west-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: token-images
          IMAGE_TAG: ${{ github.sha }}
          AWS_REGION: eu-west-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
        run: |
          docker build --platform linux/amd64 . --no-cache -t token-images --build-arg GITHUB_TOKEN=${{ secrets.GH_TOKEN }} --build-arg GITHUB_USERNAME=${{ secrets.GH_USERNAME }} --build-arg GIT_REPO_URL=${{ secrets.GIT_REPO_URL }} --build-arg RAILWAY_GIT_BRANCH=${{ github.ref_name }} --build-arg RAILWAY_GIT_COMMIT_SHA=${{ github.sha }}
          docker tag token-images $REGISTRY/$REPOSITORY:$GITHUB_SHA
          docker push $REGISTRY/$REPOSITORY:$GITHUB_SHA
